[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
